title: Alexandre Pellan Cheng
subtitle: Next Generation Cancer Monitoring Tools
description: My research focuses on wet- and dry-lab technology development for noninvassive cancer detection and characterization.
header: images/background.png
footer: images/background.png
links:
  orcid: 0000-0002-3667-0992
  google-scholar: txVdvdQAAAAJ
  twitter: AlexandrePCheng
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@alexpcheng.com
twitter: alexpcheng
youtube: alexpcheng
